<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
             schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_web_ui</name>
  <version>0.1.0</version>
  <description>Mobile Web controls for manual robot motion and mode selection.</description>
  <maintainer email="20twenty.degree@gmail.com">xxf1ow</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>nlohmann-json3-dev</build_depend>
  <build_depend>openssl</build_depend>
  <build_depend>tl-expected</build_depend>
  <build_depend>yaml-cpp</build_depend>
  <build_depend>zlib</build_depend>

  <exec_depend>nlohmann-json3-dev</exec_depend>
  <exec_depend>openssl</exec_depend>
  <exec_depend>tl-expected</exec_depend>
  <exec_depend>yaml-cpp</exec_depend>
  <exec_depend>zlib</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
